### ISSUE TITLE
Aldonu la grupon Kontraŭkapitalismo

### ISSUE THREAD

**Issue by nicolasmaia** [RobinvanderVliet/Telegramo.org#4]
https://t.me/joinchat/AAAAAEIj1q9PIYIwhAqQTQ

**Comment by bvanrijn** [comment]
Bedaŭrinde, la ligilo ne plu funkcias.

**Comment by nicolasmaia** [comment]
Dankon @bvanrijn! Jen la nova ligilo https://t.me/joinchat/AAAAAEIj1q8Rxgs2e8fzBQ

**Comment by bvanrijn** [comment]
Mi pensas ke tio estas sufiĉe facile aldoni. Eble mi povas fari ĝin en la fontkodo.

**Comment by nicolasmaia** [comment]
Malfeliĉe ne. Mi klopodis fari ĝin, sed mi konstatis, ke nur @RobinvanderVliet havas aliron al `grupoj.json`, kie estas la gruplisto.

**Comment by bvanrijn** [comment]
Sed kie estas tiu dosiero? :/

**Comment by nicolasmaia** [comment]
En .gitignore, ĉar ĝi havs personajn informojn pri vivantaj homoj.

**Comment by RobinvanderVliet** [comment]
Mi jam aldonis la grupon antaŭlonge. Mi forigis ĉiujn personajn (sed publike haveblajn) informojn el grupoj.json kaj mi aldonis ĝin al la deponejo per 74d12ba.
